mito/views/companies.py
from flask import Blueprint, request, flash, redirect, url_for, abort
from flask_login import login_required, current_user
from flasksr import LayoutSR, Component, Dom, Layout

from mito.decorators import roles_required
from mito.render_helpers import common_page, companies_page
from mito.entities import Company
from mito.services import company_service

mod = Blueprint('companies', __name__, )


@mod.route('/', methods=["GET"])
@login_required
def index():
    return LayoutSR(
        Component('companies-actions', companies_page.render_companies_action_buttons),
        Component('companies', companies_page.render_active_companies),
        layout=Layout(companies_page.render_layout),
        pre_stream=(Dom(common_page.render_pre_body),
                    Dom(common_page.render_top_menu, current_user.is_authenticated)),
        post_stream=Dom(common_page.render_post_body)
    ).response


@mod.route('/all', methods=["GET"])
@login_required
def all_companies():
    return LayoutSR(
        Component('companies-actions', companies_page.render_companies_action_buttons),
        Component('companies', companies_page.render_all_companies),
        layout=Layout(companies_page.render_layout),
        pre_stream=(Dom(common_page.render_pre_body),
                    Dom(common_page.render_top_menu, current_user.is_authenticated)),
        post_stream=Dom(common_page.render_post_body)
    ).response


@mod.route('/add', methods=["GET", "POST"])
@login_required
@roles_required('admin')
def add_company():
    if request.method == 'GET':
        return LayoutSR(
            Component('company-add-form', companies_page.render_company_add_form),
            layout=Layout(companies_page.render_layout_company_add),
            pre_stream=(Dom(common_page.render_pre_body),
                        Dom(common_page.render_top_menu, current_user.is_authenticated)),
            post_stream=Dom(common_page.render_post_body)
        ).response

    company_name = request.form.get('company_name')
    company_display_name = request.form.get('display_name')
    company_icon64 = request.form.get('icon64')
    company_icon256 = request.form.get('icon256')

    if not company_name:
        abort(400)

    company = Company(name=company_name, display_name=company_display_name,
                      icon64=company_icon64, icon256=company_icon256,
                      is_active=True)
    company, error = company_service.create_company(company)

    if error:
        flash(error.description, 'error')

    return redirect(url_for('companies.index'))


@mod.route('/edit/<company_name>', methods=["GET", "POST"])
@login_required
@roles_required('admin')
def edit_company(company_name):
    if request.method == 'GET':
        return LayoutSR(
            Component('company-edit-form', companies_page.render_company_edit_form, company_name),
            layout=Layout(companies_page.render_layout_company_edit),
            pre_stream=(Dom(common_page.render_pre_body),
                        Dom(common_page.render_top_menu, current_user.is_authenticated)),
            post_stream=Dom(common_page.render_post_body)
        ).response

    company_display_name = request.form.get('display_name')
    company_icon64 = request.form.get('icon64')
    company_icon256 = request.form.get('icon256')
    company_is_active = request.form.get('is_active') or False

    if company_is_active == 'on':
        company_is_active = True

    company = Company(name=company_name, display_name=company_display_name,
                      icon64=company_icon64, icon256=company_icon256,
                      is_active=company_is_active)

    company, error = company_service.update_company(company)

    if error:
        flash(error.description, 'error')

    return redirect(url_for('companies.index'))

mito/templates/companies_page/companies.html
<div class="ui segment">
    {% for company in companies %}
    <div class="ui segment">
        <div class="ui header">
            <h3>
                <a href="{{url_for('companies.edit_company', company_name=company.name)}}">{{company.display_name}}</a>
            </h3>
        </div>
        <div class="ui divider"></div>
        <div class="ui form">
            <div class="field">
                <label>Name</label>
                <input type="text" readonly value="{{company.name}}"/>
            </div>
            <div class="field">
                <label>Active?</label>
                <input type="text" readonly value="{{company.is_active}}"/>
            </div>
            <div class="field">
                <label>Icon (64x64)</label>
                <input type="text" readonly value="{{company.icon64}}"/>
            </div>
            <div class="field">
                <label>Icon (256x256)</label>
                <input type="text" readonly value="{{company.icon256}}"/>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

mito/templates/companies_page/companies_actions.html
<div class="ui buttons">
    <a class="ui button" href="{{url_for('companies.add_company')}}">Add a new company</a>
</div>

mito/templates/companies_page/company_add_form.html
<form class="ui form" method="POST" action="{{url_for('companies.add_company')}}">
    <div class="field">
        <label>Name</label>
        <input type="text" name="company_name" placeholder="Unique name for company">
    </div>
    <div class="field">
        <label>Display Name</label>
        <input type="text" name="display_name" placeholder="Display name for company">
    </div>
    <div class="field">
        <label>Small Icon URL</label>
        <input type="text" name="icon64" placeholder="URL for icon (64x64)">
    </div>
    <div class="field">
        <label>Large Icon URL</label>
        <input type="text" name="icon256" placeholder="URL for icon (256x256)">
    </div>
    <div class="field">
        <button class="ui button" type="submit">Submit</button>
    </div>
</form>

mito/templates/companies_page/company_add_form_layout.html
<div class="ui one column grid">
    <div class="column">
        <div ref-sr-id="company-add-form"></div>
    </div>
</div>

mito/templates/companies_page/company_edit_form.html
<form class="ui form" method="POST" action="{{url_for('companies.edit_company', company_name=company.name)}}">
    <div class="field">
        <label>Name</label>
        <input type="text" name="company_name" placeholder="Unique name for company" value="{{company.name}}">
    </div>
    <div class="field">
        <label>Display Name</label>
        <input type="text" name="display_name" placeholder="Display name for company" value="{{company.display_name}}">
    </div>
    <div class="field">
        <div class="ui checkbox">
            <label>Is Active?</label>
            <input name="is_active" type="checkbox" tabindex="0" class="hidden" {% if company.is_active %}checked{% endif %}>
        </div>
    </div>
    <div class="field">
        <label>Small Icon URL</label>
        <input type="text" name="icon64" placeholder="URL for icon (64x64)" value="{{company.icon64}}">
    </div>
    <div class="field">
        <label>Large Icon URL</label>
        <input type="text" name="icon256" placeholder="URL for icon (256x256)" value="{{company.icon256}}">
    </div>
    <div class="field">
        <button class="ui button" type="submit">Save</button>
    </div>
</form>

mito/templates/companies_page/company_edit_form_layout.html
<div class="ui one column grid">
    <div class="column">
        <div ref-sr-id="company-edit-form"></div>
    </div>
</div>

mito/templates/companies_page/layout.html
<div class="ui one column grid">
    <div class="column">
        <div ref-sr-id="companies-actions"></div>
        <div ref-sr-id="companies"></div>
    </div>
</div>