mito/views/user_subscriptions.py
from flask import Blueprint, request, flash, redirect, url_for
from flask_login import login_required, current_user
from flasksr import LayoutSR, Component, Dom, Layout

from mito.render_helpers import common_page, user_subscriptions_page
from mito.entities import UserSubscription
from mito.services import user_subscriptions_service

mod = Blueprint('user_subscriptions', __name__, )


@mod.route('/', methods=["GET"])
@login_required
def index():
    return LayoutSR(
        Component('user-subscription-actions', user_subscriptions_page.render_user_subscriptions_action_buttons),
        Component('user-subscriptions', user_subscriptions_page.render_user_subscription, current_user.id),
        Component('unsubscribed-companies', user_subscriptions_page.render_user_unsubscribed_companies, current_user.id),
        layout=Layout(user_subscriptions_page.render_layout),
        pre_stream=(Dom(common_page.render_pre_body),
                    Dom(common_page.render_top_menu, current_user.is_authenticated)),
        post_stream=Dom(common_page.render_post_body)
    ).response


@mod.route('/create', methods=["POST"])
@login_required
def create_subscription():
    user_id = current_user.id
    user_subscription = UserSubscription(user_id=user_id, company_ids=[])
    user_subscription, error = user_subscriptions_service.create_user_subscription(user_subscription)

    if error:
        return jsonify(error.jsonify())

    return redirect(url_for('user_subscriptions.index'))


@mod.route('/company/<company_id>/subscribe', methods=["POST"])
@login_required
def subscribe_to_company(company_id):
    user_id = current_user.id
    user_subscription, error = user_subscriptions_service.subscribe_to_company(user_id, company_id)

    if error:
        return jsonify(error.jsonify())

    return redirect(url_for('user_subscriptions.index'))


@mod.route('/company/<company_id>/unsubscribe', methods=["POST"])
@login_required
def unsubscribe_from_company(company_id):
    user_id = current_user.id
    user_subscription, error = user_subscriptions_service.unsubscribe_from_company(user_id, company_id)

    if error:
        return jsonify(error.jsonify())

    return redirect(url_for('user_subscriptions.index'))

mito/templates/user_subscriptions_page/layout.html
<div class="ui one column grid">
    <div class="column">
        <div ref-sr-id="user-subscription-actions"></div>
        <div ref-sr-id="user-subscriptions"></div>
    </div>
</div>

mito/templates/user_subscriptions_page/user_subscriptions.html
<div class="ui segment">
    {% if user_subscription == None %}
    <form class="ui form" method="POST" action="{{url_for('user_subscriptions.create_subscription')}}">
        <div class="ui field">
            <button class="ui button" type="submit">Create your first subscription</button>
        </div>
    </form>
    {% else %}
        <div class="ui form">
            <div class="ui field">
                <label>Companies you subscribed to</label>
                <div class="ui list">
                    {% for company in user_subscription.companies %}
                        <div class="ui item">
                            <form class="ui form" method="POST" action="{{url_for('user_subscriptions.unsubscribe_from_company', company_id=company.id)}}">
                                <div class="field">
                                    <label>{{company.display_name}}</label>
                                    <button type="submit">Unsubscribe</button>
                                </div>
                            </form>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
</div>

mito/templates/user_subscriptions_page/user_subscriptions_actions.html
<div class="ui buttons">
    Subscriptions Buttons Here
</div>

mito/templates/user_subscriptions_page/user_unsubscribed_companies.html
<div class="ui list">
    {% for company in unsubscribed_companies %}
    <div class="ui item">
        <form class="ui form" method="POST" action="{{url_for('user_subscriptions.subscribe_to_company', company_id=company.id)}}">
            <div class="field">
                <label>{{company.display_name}}</label>
                <button type="submit">Subscribe</button>
            </div>
        </form>
    </div>
    {% endfor %}
</div>