mito/views/pages.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user, logout_user
from flasksr import LayoutSR, Component, Dom, Layout

from mito import github
from mito.render_helpers import index_page, common_page, dashboard_page

mod = Blueprint('pages', __name__, )


@mod.route('/', methods=["GET", "POST"])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('pages.dashboard'))

    return LayoutSR(
        Component('main-content', index_page.render_main_content),
        layout=Layout(index_page.render_layout),
        pre_stream=(Dom(common_page.render_pre_body),
                    Dom(common_page.render_top_menu, current_user.is_authenticated)),
        post_stream=Dom(common_page.render_post_body)
    ).response


@mod.route('/login', methods=["GET"])
def login():
    return github.authorize('user:email')


@mod.route('/logout', methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('pages.index'))


@mod.route('/dashboard', methods=["GET"])
@login_required
def dashboard():
    return LayoutSR(
        Component('pending-articles', dashboard_page.render_pending_articles),
        layout=Layout(dashboard_page.render_layout),
        pre_stream=(Dom(common_page.render_pre_body),
                    Dom(common_page.render_top_menu, is_authenticated=current_user.is_authenticated)),
        post_stream=Dom(common_page.render_post_body)
    ).response

mito/views/user.py
from flask import Blueprint, request
from flask_login import login_required, current_user
from flasksr import LayoutSR, Component, Dom, Layout

from mito.render_helpers import common_page, user_page
from mito.entities import User
from mito.services import user_service

mod = Blueprint('user', __name__, )


@mod.route('/', methods=["GET"])
@login_required
def index():
    return LayoutSR(
        Component('user-actions', user_page.render_user_action_buttons),
        Component('user-profile', user_page.render_user_profile, current_user.id),
        layout=Layout(user_page.render_layout),
        pre_stream=(Dom(common_page.render_pre_body),
                    Dom(common_page.render_top_menu, current_user.is_authenticated)),
        post_stream=Dom(common_page.render_post_body)
    ).response

mito/templates/menus/top_menu.html
<div class="ui inverted black borderless menu top">
    <a href="{{url_for('pages.index')}}" class="item">
        Mito
    </a>
    {% if is_authenticated %}
        <a href="{{url_for('articles.index')}}" class="item">Articles</a>
        <a href="{{url_for('companies.index')}}" class="item">Companies</a>
        <a href="{{url_for('user_subscriptions.index')}}" class="item">Subscriptions</a>
        <a href="{{url_for('user.index')}}" class="item">Profile</a>
        <a href="{{url_for('user_management.index')}}" class="item">Manage Users</a>
        <a href="{{url_for('pages.logout')}}" class="item">Logout</a>
    {% else %}
        <a href="{{url_for('pages.login')}}" class="item">Login with Github</a>
    {% endif %}
</div>