mito/views/article.py
from flask import Blueprint
from flask_login import login_required, current_user
from flasksr import LayoutSR, Component, Dom, Layout

from mito.render_helpers import article_page, common_page

mod = Blueprint('article', __name__, )


@mod.route('/<article_id>', methods=["GET"])
@login_required
def get_note(article_id):
    return "Article for id: " + article_id


@mod.route('/<article_id>/redirect', methods=["GET"])
@login_required
def redirect_to_original():
    return "Redirecting article to original source article"


@mod.route('/<article_id>/mark/read', methods=["POST"])
@login_required
def mark_article_read():
    return "Mark article as read"


@mod.route('/<article_id>/mark/bookmark', methods=["POST"])
@login_required
def mark_article_bookmark():
    return "Mark article as bookmark"


@mod.route('/<article_id>/mark/like', methods=["POST"])
@login_required
def mark_article_as_liked():
    return "Mark article as liked"

mito/views/articles.py
from flask import Blueprint, jsonify
from flask_login import login_required, current_user
from flasksr import LayoutSR, Component, Dom, Layout

from mito.decorators import roles_required
from mito.render_helpers import common_page, articles_page
from mito.services import user_bucket_service, recommendation_service

mod = Blueprint('articles', __name__, )


@mod.route('/', methods=["GET"])
@login_required
def index():
    return LayoutSR(
        Component('articles-home-actions', articles_page.render_articles_home_action_buttons),
        layout=Layout(articles_page.render_articles_home_layout),
        pre_stream=(Dom(common_page.render_pre_body),
                    Dom(common_page.render_top_menu, current_user.is_authenticated)),
        post_stream=Dom(common_page.render_post_body)
    ).response


@mod.route('/<bucket_name>', methods=["GET"])
@login_required
def get_articles_from_bucket(bucket_name):
    return LayoutSR(
        Component('articles-actions', articles_page.render_articles_action_buttons),
        Component('articles', articles_page.render_articles, current_user.id, bucket_name),
        layout=Layout(articles_page.render_layout),
        pre_stream=(Dom(common_page.render_pre_body),
                    Dom(common_page.render_top_menu, current_user.is_authenticated)),
        post_stream=Dom(common_page.render_post_body)
    ).response


@mod.route('/unread/populate', methods=["POST"])
@login_required
def populate_from_bucket():
    """Takes articles from recommended into puts them into unread
    """
    user_id = current_user.id
    actual_moved, error = user_bucket_service.move_articles(user_id, 'recommended', 'unread', count=5)
    return redirect(url_for('articles.index'))


@mod.route('/recommended/populate/<user_id>', methods=["POST"])
@login_required
@roles_required('admin')
def recommend_articles(user_id):
    move_count, error = recommendation_service.recommend_articles(user_id)
    if error:
        return jsonify(error.jsonify())
    return jsonify(count=0)

mito/templates/articles_page/articles.html
<div class="ui segment">
  <h3><a href="{{url_for('articles.index')}}">Articles</a></h3>
  <div class="ui divider"></div>
  <div>
    <div class="ui grey header">
      <h4>23rd December, 2016
        <button class="ui right floated tiny basic grey button">
          <i class="icon pencil"></i>Edit
        </button>
      </h4>
    </div>
    <div class="content">
      This is the complte content. HTML rendered
    </div>
  </div>
</div>

mito/templates/articles_page/articles_actions.html
<h1>
    Articles action buttons
</h1>

mito/templates/articles_page/articles_home_actions.html
<div class="ui list">
    <div class="ui item">
        <a href="{{url_for('articles.get_articles_from_bucket', bucket_name='unread')}}">Unread Articles</a>
    </div>
    <div class="ui item">
        <a href="{{url_for('articles.get_articles_from_bucket', bucket_name='read')}}">Read Articles</a>
    </div>
    <div class="ui item">
        <a href="{{url_for('articles.get_articles_from_bucket', bucket_name='recommended')}}">Recommended Articles</a>
    </div>
    <div class="ui item">
        <form class="ui form" method="POST" action="{{url_for('articles.populate_from_bucket')}}">
            <input type="submit" class="ui button" value="Populate Unread Articles"></input>
        </form>
    </div>
</div>

mito/templates/articles_page/home_layout.html
<div class="ui one column grid">
  <div class="column">
    <div ref-sr-id="articles-home-actions"></div>
  </div>
</div>

mito/templates/articles_page/layout.html
<div class="ui one column grid">
  <div class="column">
    <div ref-sr-id="articles"></div>
  </div>
</div>

mito/templates/articles_page/pending_articles.html
<div class="ui segment">
  <h3><a href="{{url_for('articles.index')}}">Pending Articles</a></h3>
  <div class="ui divider"></div>
  <div>
    <div class="ui grey header">
      <h4>23rd December, 2016
        <button class="ui right floated tiny basic grey button">
          <i class="icon pencil"></i>Edit
        </button>
      </h4>
    </div>
    <div class="content">
      This is the complte content. HTML rendered
    </div>
  </div>
</div>